/* PAGES */
export const TITLE_UPDATE = 'TITLE_UPDATE'

/* SETTINGS */
export const LOAD_USER = 'LOAD_USER'

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'
export const PASSWORD_COPY_TO_CLIPBOARD = 'PASSWORD_COPY_TO_CLIPBOARD'
export const LOGOUT_USER = 'LOGOUT_USER'
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'

/* NOTIFICATION CENTER */
export const DISMISS_ERROR = 'DISMISS_ERROR'
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION'

/* COMMON ERROR */
export const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR'

/* BLOG */
export const BLOG_CREATED = 'BLOG_CREATED'
export const BLOG_UPDATED = 'BLOG_UPDATED'
export const BLOG_DELETED = 'BLOG_DELETED'
